/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package cl.atromilen.kafkastreams.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class MovieAvro extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -7857429484926818276L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"MovieAvro\",\"namespace\":\"cl.atromilen.kafkastreams.avro\",\"fields\":[{\"name\":\"name\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"director\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"cast\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},\"default\":[]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<MovieAvro> ENCODER =
      new BinaryMessageEncoder<MovieAvro>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<MovieAvro> DECODER =
      new BinaryMessageDecoder<MovieAvro>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<MovieAvro> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<MovieAvro> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<MovieAvro> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<MovieAvro>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this MovieAvro to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a MovieAvro from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a MovieAvro instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static MovieAvro fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.String name;
  @Deprecated public java.lang.String director;
  @Deprecated public java.util.List<java.lang.String> cast;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public MovieAvro() {}

  /**
   * All-args constructor.
   * @param name The new value for name
   * @param director The new value for director
   * @param cast The new value for cast
   */
  public MovieAvro(java.lang.String name, java.lang.String director, java.util.List<java.lang.String> cast) {
    this.name = name;
    this.director = director;
    this.cast = cast;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return name;
    case 1: return director;
    case 2: return cast;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: name = value$ != null ? value$.toString() : null; break;
    case 1: director = value$ != null ? value$.toString() : null; break;
    case 2: cast = (java.util.List<java.lang.String>)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'name' field.
   * @return The value of the 'name' field.
   */
  public java.lang.String getName() {
    return name;
  }


  /**
   * Sets the value of the 'name' field.
   * @param value the value to set.
   */
  public void setName(java.lang.String value) {
    this.name = value;
  }

  /**
   * Gets the value of the 'director' field.
   * @return The value of the 'director' field.
   */
  public java.lang.String getDirector() {
    return director;
  }


  /**
   * Sets the value of the 'director' field.
   * @param value the value to set.
   */
  public void setDirector(java.lang.String value) {
    this.director = value;
  }

  /**
   * Gets the value of the 'cast' field.
   * @return The value of the 'cast' field.
   */
  public java.util.List<java.lang.String> getCast() {
    return cast;
  }


  /**
   * Sets the value of the 'cast' field.
   * @param value the value to set.
   */
  public void setCast(java.util.List<java.lang.String> value) {
    this.cast = value;
  }

  /**
   * Creates a new MovieAvro RecordBuilder.
   * @return A new MovieAvro RecordBuilder
   */
  public static cl.atromilen.kafkastreams.avro.MovieAvro.Builder newBuilder() {
    return new cl.atromilen.kafkastreams.avro.MovieAvro.Builder();
  }

  /**
   * Creates a new MovieAvro RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new MovieAvro RecordBuilder
   */
  public static cl.atromilen.kafkastreams.avro.MovieAvro.Builder newBuilder(cl.atromilen.kafkastreams.avro.MovieAvro.Builder other) {
    if (other == null) {
      return new cl.atromilen.kafkastreams.avro.MovieAvro.Builder();
    } else {
      return new cl.atromilen.kafkastreams.avro.MovieAvro.Builder(other);
    }
  }

  /**
   * Creates a new MovieAvro RecordBuilder by copying an existing MovieAvro instance.
   * @param other The existing instance to copy.
   * @return A new MovieAvro RecordBuilder
   */
  public static cl.atromilen.kafkastreams.avro.MovieAvro.Builder newBuilder(cl.atromilen.kafkastreams.avro.MovieAvro other) {
    if (other == null) {
      return new cl.atromilen.kafkastreams.avro.MovieAvro.Builder();
    } else {
      return new cl.atromilen.kafkastreams.avro.MovieAvro.Builder(other);
    }
  }

  /**
   * RecordBuilder for MovieAvro instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<MovieAvro>
    implements org.apache.avro.data.RecordBuilder<MovieAvro> {

    private java.lang.String name;
    private java.lang.String director;
    private java.util.List<java.lang.String> cast;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(cl.atromilen.kafkastreams.avro.MovieAvro.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.name)) {
        this.name = data().deepCopy(fields()[0].schema(), other.name);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.director)) {
        this.director = data().deepCopy(fields()[1].schema(), other.director);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.cast)) {
        this.cast = data().deepCopy(fields()[2].schema(), other.cast);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing MovieAvro instance
     * @param other The existing instance to copy.
     */
    private Builder(cl.atromilen.kafkastreams.avro.MovieAvro other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.name)) {
        this.name = data().deepCopy(fields()[0].schema(), other.name);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.director)) {
        this.director = data().deepCopy(fields()[1].schema(), other.director);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.cast)) {
        this.cast = data().deepCopy(fields()[2].schema(), other.cast);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'name' field.
      * @return The value.
      */
    public java.lang.String getName() {
      return name;
    }


    /**
      * Sets the value of the 'name' field.
      * @param value The value of 'name'.
      * @return This builder.
      */
    public cl.atromilen.kafkastreams.avro.MovieAvro.Builder setName(java.lang.String value) {
      validate(fields()[0], value);
      this.name = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'name' field has been set.
      * @return True if the 'name' field has been set, false otherwise.
      */
    public boolean hasName() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'name' field.
      * @return This builder.
      */
    public cl.atromilen.kafkastreams.avro.MovieAvro.Builder clearName() {
      name = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'director' field.
      * @return The value.
      */
    public java.lang.String getDirector() {
      return director;
    }


    /**
      * Sets the value of the 'director' field.
      * @param value The value of 'director'.
      * @return This builder.
      */
    public cl.atromilen.kafkastreams.avro.MovieAvro.Builder setDirector(java.lang.String value) {
      validate(fields()[1], value);
      this.director = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'director' field has been set.
      * @return True if the 'director' field has been set, false otherwise.
      */
    public boolean hasDirector() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'director' field.
      * @return This builder.
      */
    public cl.atromilen.kafkastreams.avro.MovieAvro.Builder clearDirector() {
      director = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'cast' field.
      * @return The value.
      */
    public java.util.List<java.lang.String> getCast() {
      return cast;
    }


    /**
      * Sets the value of the 'cast' field.
      * @param value The value of 'cast'.
      * @return This builder.
      */
    public cl.atromilen.kafkastreams.avro.MovieAvro.Builder setCast(java.util.List<java.lang.String> value) {
      validate(fields()[2], value);
      this.cast = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'cast' field has been set.
      * @return True if the 'cast' field has been set, false otherwise.
      */
    public boolean hasCast() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'cast' field.
      * @return This builder.
      */
    public cl.atromilen.kafkastreams.avro.MovieAvro.Builder clearCast() {
      cast = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public MovieAvro build() {
      try {
        MovieAvro record = new MovieAvro();
        record.name = fieldSetFlags()[0] ? this.name : (java.lang.String) defaultValue(fields()[0]);
        record.director = fieldSetFlags()[1] ? this.director : (java.lang.String) defaultValue(fields()[1]);
        record.cast = fieldSetFlags()[2] ? this.cast : (java.util.List<java.lang.String>) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<MovieAvro>
    WRITER$ = (org.apache.avro.io.DatumWriter<MovieAvro>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<MovieAvro>
    READER$ = (org.apache.avro.io.DatumReader<MovieAvro>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.name);

    out.writeString(this.director);

    long size0 = this.cast.size();
    out.writeArrayStart();
    out.setItemCount(size0);
    long actualSize0 = 0;
    for (java.lang.String e0: this.cast) {
      actualSize0++;
      out.startItem();
      out.writeString(e0);
    }
    out.writeArrayEnd();
    if (actualSize0 != size0)
      throw new java.util.ConcurrentModificationException("Array-size written was " + size0 + ", but element count was " + actualSize0 + ".");

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.name = in.readString();

      this.director = in.readString();

      long size0 = in.readArrayStart();
      java.util.List<java.lang.String> a0 = this.cast;
      if (a0 == null) {
        a0 = new SpecificData.Array<java.lang.String>((int)size0, SCHEMA$.getField("cast").schema());
        this.cast = a0;
      } else a0.clear();
      SpecificData.Array<java.lang.String> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<java.lang.String>)a0 : null);
      for ( ; 0 < size0; size0 = in.arrayNext()) {
        for ( ; size0 != 0; size0--) {
          java.lang.String e0 = (ga0 != null ? ga0.peek() : null);
          e0 = in.readString();
          a0.add(e0);
        }
      }

    } else {
      for (int i = 0; i < 3; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.name = in.readString();
          break;

        case 1:
          this.director = in.readString();
          break;

        case 2:
          long size0 = in.readArrayStart();
          java.util.List<java.lang.String> a0 = this.cast;
          if (a0 == null) {
            a0 = new SpecificData.Array<java.lang.String>((int)size0, SCHEMA$.getField("cast").schema());
            this.cast = a0;
          } else a0.clear();
          SpecificData.Array<java.lang.String> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<java.lang.String>)a0 : null);
          for ( ; 0 < size0; size0 = in.arrayNext()) {
            for ( ; size0 != 0; size0--) {
              java.lang.String e0 = (ga0 != null ? ga0.peek() : null);
              e0 = in.readString();
              a0.add(e0);
            }
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










